//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_incidents.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents_History
    {
        public int Id { get; set; }
        public int IdIncident { get; set; }
        public Nullable<int> IdWorker { get; set; }
        public System.DateTime DateOfIncident { get; set; }
        public string IncidentName { get; set; }
        public string ImportanceOfIncident { get; set; }
        public string Description { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
